services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: todoapp
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - 3306:3306
    networks:
      - todoappnetwork

  backend:
    build:
      context: backend
    ports:
      - "3000:3000"
    networks:
      - todoappnetwork
    volumes:
      - backend_node_modules:/workspace/server/node_modules
      - .:/workspace

  frontend:
    build:
      context: frontend
    ports:
      - "5173:5173"
    networks:
      - todoappnetwork
    volumes:
      - frontend_node_modules:/workspace/frontend/node_modules
      - .:/workspace
networks:
  todoappnetwork:
volumes:
  backend_node_modules:
  frontend_node_modules: